# Generated by Django 5.1.1 on 2024-10-06 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messwithpaperwork', '0002_alter_testset_model_alter_testset_nomenclature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testset',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
